-- Active: 1704963434667@@192.168.1.23@3306@home_inventory
DROP TABLE IF EXiSTS ITEM_TYPES;
DROP TABLE IF EXISTS ITEM_IMAGES_URLS;
DROP TABLE IF EXISTS MANUFATURERS;
DROP TABLE IF EXiSTS PURCHASE_HISTORY;
DROP TABLE IF EXiSTS STORES;
DROP TABLE IF EXiSTS ITEM_MASTER;
DROP TABLE IF EXiSTS LOCATION_MASTER;
DROP TABLE IF EXiSTS SOH;

CREATE TABLE ITEM_TYPES (
    type_id INT PRIMARY KEY
)

CREATE TABLE ITEM_MASTER (
    item_number INT PRIMARY KEY,
    alt_item_number INT,
    descr varchar(64),
    barcode varchar(20),
    item_weight INT,
    item_height INT,
    item_width INT,
    image_link_ID INT,
    item_type int REFERENCES ITEM_TYPES (type_id),
    manufacturer_ID INT
)

CREATE TABLE ITEM_IMAGES_URLS (
    the_item INT REFERENCES ITEM_MASTER(item_number),
    the_image_url varchar(112)
)
